#!/usr/bin/env python3
"""Generate rx81_shim.s: route retroXt81's X/Xt helper calls to xwp's OWN static Xlib.
Each stub tail-jumps to the byte-exact static entry (from wp81_fullsyms.s), preserving
args verbatim (variadic-safe).  Helpers absent from xwp (never linked) become no-ops.
Re-run if the mapped addresses change, then `make` in wp81port/."""
SYMS='/home/andrew/Programming/Projects/wordperfect-8-lin/wp8-modern/installer/wp81port/wp81_fullsyms.s'
OUT ='/home/andrew/Programming/Projects/wordperfect-8-lin/wp8-modern/installer/wp81port/rx81_shim.s'

# addresses from the full symbol map
BASE=0x0864d9d0; cur=BASE; addr={}
for line in open(SYMS):
    s=line.strip()
    if s.startswith('.org'): cur=BASE+int(s.split()[1],16)
    elif s.endswith(':') and not s.startswith('.'): addr[s[:-1]]=cur

# helpers pinned by hand from the crash loop (drifted / disambiguated, not in the auto map)
addr.update({'XFlush':0x08679850,        # disambiguated from XFree @0x0868b0e0
             'XtVaGetValues':0x08674990, # prefix 209/417B (drifted)
             'XtAddEventHandler':0x086568b0,
             'XFreeFontInfo':0x086b2b50})

# XCopyGC is NOT linked in xwp (WP never calls it; CopyGC.o dropped) -> harmless no-op.
NOOP={'XCopyGC'}

# the exact set retroXt81 imports (nm -D retroXt81.so | awk '$1=="U"' | grep X)
HELPERS="""XAllocColor XCopyGC XCreateGC XCreateImage XCreatePixmap XExtentsOfFontSet XFlush
XFreeFontInfo XFreeGC XFreePixmap XGetGCValues XQueryColor XQueryFont XSetForeground
XtAddCallback XtAddEventHandler XtAppAddTimeOut XtCallCallbacks XtDisplayOfObject XtHasCallbacks
XtIsManaged XtIsSensitive XtName XtTranslateCoords XtVaGetValues XtVaSetValues
XtWidgetToApplicationContext XtWindowOfObject XtWindowToWidget""".split()

missing=[h for h in HELPERS if h not in addr and h not in NOOP]
assert not missing, f"unresolved helpers: {missing}"

with open(OUT,'w') as o:
    o.write("/* rx81_shim.s -- GENERATED by scratchpad/gen_rx81_shim.py.  Route retroXt81's X/Xt\n")
    o.write(" * helper calls to xwp's OWN static Xlib (single-instance: static libX11/libXt owns the\n")
    o.write(" * Display+widget tree, so no modern 2nd instance ever touches xwp's ancient Display --\n")
    o.write(" * that avoids the _XReply/_XSend SIGSEGV).  Each stub tail-jumps to the byte-exact\n")
    o.write(" * static entry (XFree86 3.3.2 map), preserving args verbatim (variadic-safe).\n")
    o.write(" * XCopyGC: absent in xwp -> harmless ret (clip-copy skipped, cosmetic).\n")
    o.write(" * .hidden is CRUCIAL: it keeps these out of the .so's DYNAMIC symbol table, so\n")
    o.write(" * retroXt's own calls still bind here, but the stubs NEVER interpose a\n")
    o.write(" * dynamically-linked binary's X calls (e.g. WP 8.0) -- which would tail-jump its\n")
    o.write(" * calls into 8.1's hardcoded static addresses and crash it, bypassing the MD5 guard.\n")
    o.write(" * Build: as --32 -o rx81_shim.o rx81_shim.s */\n\t.text\n")
    for h in HELPERS:
        o.write(f"\t.globl {h}\n\t.hidden {h}\n\t.type {h},@function\n{h}:\n")
        if h in NOOP:
            o.write("\txor %eax,%eax\n\tret   /* absent in xwp; no-op */\n")
        else:
            o.write(f"\tjmp *.L_{h}\n.L_{h}: .long 0x{addr[h]:08x}\n")
    o.write("\n")
print(f"wrote {len(HELPERS)-len(NOOP)} static routes + {len(NOOP)} no-op -> {OUT}")
