/* rx81_shim.s -- GENERATED by scratchpad/gen_rx81_shim.py.  Route retroXt81's X/Xt
 * helper calls to xwp's OWN static Xlib (single-instance: static libX11/libXt owns the
 * Display+widget tree, so no modern 2nd instance ever touches xwp's ancient Display --
 * that avoids the _XReply/_XSend SIGSEGV).  Each stub tail-jumps to the byte-exact
 * static entry (XFree86 3.3.2 map), preserving args verbatim (variadic-safe).
 * XCopyGC: absent in xwp -> harmless ret (clip-copy skipped, cosmetic).
 * .hidden is CRUCIAL: it keeps these out of the .so's DYNAMIC symbol table, so
 * retroXt's own calls still bind here, but the stubs NEVER interpose a
 * dynamically-linked binary's X calls (e.g. WP 8.0) -- which would tail-jump its
 * calls into 8.1's hardcoded static addresses and crash it, bypassing the MD5 guard.
 * Build: as --32 -o rx81_shim.o rx81_shim.s */
	.text
	.globl XAllocColor
	.hidden XAllocColor
	.type XAllocColor,@function
XAllocColor:
	jmp *.L_XAllocColor
.L_XAllocColor: .long 0x0867aa50
	.globl XCopyGC
	.hidden XCopyGC
	.type XCopyGC,@function
XCopyGC:
	xor %eax,%eax
	ret   /* absent in xwp; no-op */
	.globl XCreateGC
	.hidden XCreateGC
	.type XCreateGC,@function
XCreateGC:
	jmp *.L_XCreateGC
.L_XCreateGC: .long 0x08678030
	.globl XCreateImage
	.hidden XCreateImage
	.type XCreateImage,@function
XCreateImage:
	jmp *.L_XCreateImage
.L_XCreateImage: .long 0x0867bb40
	.globl XCreatePixmap
	.hidden XCreatePixmap
	.type XCreatePixmap,@function
XCreatePixmap:
	jmp *.L_XCreatePixmap
.L_XCreatePixmap: .long 0x08678710
	.globl XExtentsOfFontSet
	.hidden XExtentsOfFontSet
	.type XExtentsOfFontSet,@function
XExtentsOfFontSet:
	jmp *.L_XExtentsOfFontSet
.L_XExtentsOfFontSet: .long 0x08694720
	.globl XFlush
	.hidden XFlush
	.type XFlush,@function
XFlush:
	jmp *.L_XFlush
.L_XFlush: .long 0x08679850
	.globl XFreeFontInfo
	.hidden XFreeFontInfo
	.type XFreeFontInfo,@function
XFreeFontInfo:
	jmp *.L_XFreeFontInfo
.L_XFreeFontInfo: .long 0x086b2b50
	.globl XFreeGC
	.hidden XFreeGC
	.type XFreeGC,@function
XFreeGC:
	jmp *.L_XFreeGC
.L_XFreeGC: .long 0x0867a060
	.globl XFreePixmap
	.hidden XFreePixmap
	.type XFreePixmap,@function
XFreePixmap:
	jmp *.L_XFreePixmap
.L_XFreePixmap: .long 0x0867a0f0
	.globl XGetGCValues
	.hidden XGetGCValues
	.type XGetGCValues,@function
XGetGCValues:
	jmp *.L_XGetGCValues
.L_XGetGCValues: .long 0x0868f960
	.globl XQueryColor
	.hidden XQueryColor
	.type XQueryColor,@function
XQueryColor:
	jmp *.L_XQueryColor
.L_XQueryColor: .long 0x08682f00
	.globl XQueryFont
	.hidden XQueryFont
	.type XQueryFont,@function
XQueryFont:
	jmp *.L_XQueryFont
.L_XQueryFont: .long 0x08679ce0
	.globl XSetForeground
	.hidden XSetForeground
	.type XSetForeground,@function
XSetForeground:
	jmp *.L_XSetForeground
.L_XSetForeground: .long 0x08685cc0
	.globl XtAddCallback
	.hidden XtAddCallback
	.type XtAddCallback,@function
XtAddCallback:
	jmp *.L_XtAddCallback
.L_XtAddCallback: .long 0x0864de10
	.globl XtAddEventHandler
	.hidden XtAddEventHandler
	.type XtAddEventHandler,@function
XtAddEventHandler:
	jmp *.L_XtAddEventHandler
.L_XtAddEventHandler: .long 0x086568b0
	.globl XtAppAddTimeOut
	.hidden XtAppAddTimeOut
	.type XtAppAddTimeOut,@function
XtAppAddTimeOut:
	jmp *.L_XtAppAddTimeOut
.L_XtAppAddTimeOut: .long 0x0865ebc0
	.globl XtCallCallbacks
	.hidden XtCallCallbacks
	.type XtCallCallbacks,@function
XtCallCallbacks:
	jmp *.L_XtCallCallbacks
.L_XtCallCallbacks: .long 0x0864e7a0
	.globl XtDisplayOfObject
	.hidden XtDisplayOfObject
	.type XtDisplayOfObject,@function
XtDisplayOfObject:
	jmp *.L_XtDisplayOfObject
.L_XtDisplayOfObject: .long 0x0865c020
	.globl XtHasCallbacks
	.hidden XtHasCallbacks
	.type XtHasCallbacks,@function
XtHasCallbacks:
	jmp *.L_XtHasCallbacks
.L_XtHasCallbacks: .long 0x0864e880
	.globl XtIsManaged
	.hidden XtIsManaged
	.type XtIsManaged,@function
XtIsManaged:
	jmp *.L_XtIsManaged
.L_XtIsManaged: .long 0x0865c140
	.globl XtIsSensitive
	.hidden XtIsSensitive
	.type XtIsSensitive,@function
XtIsSensitive:
	jmp *.L_XtIsSensitive
.L_XtIsSensitive: .long 0x0865c180
	.globl XtName
	.hidden XtName
	.type XtName,@function
XtName:
	jmp *.L_XtName
.L_XtName: .long 0x0865c230
	.globl XtTranslateCoords
	.hidden XtTranslateCoords
	.type XtTranslateCoords,@function
XtTranslateCoords:
	jmp *.L_XtTranslateCoords
.L_XtTranslateCoords: .long 0x08659890
	.globl XtVaGetValues
	.hidden XtVaGetValues
	.type XtVaGetValues,@function
XtVaGetValues:
	jmp *.L_XtVaGetValues
.L_XtVaGetValues: .long 0x08674990
	.globl XtVaSetValues
	.hidden XtVaSetValues
	.type XtVaSetValues,@function
XtVaSetValues:
	jmp *.L_XtVaSetValues
.L_XtVaSetValues: .long 0x086742f0
	.globl XtWidgetToApplicationContext
	.hidden XtWidgetToApplicationContext
	.type XtWidgetToApplicationContext,@function
XtWidgetToApplicationContext:
	jmp *.L_XtWidgetToApplicationContext
.L_XtWidgetToApplicationContext: .long 0x08655890
	.globl XtWindowOfObject
	.hidden XtWindowOfObject
	.type XtWindowOfObject,@function
XtWindowOfObject:
	jmp *.L_XtWindowOfObject
.L_XtWindowOfObject: .long 0x0865c0e0
	.globl XtWindowToWidget
	.hidden XtWindowToWidget
	.type XtWindowToWidget,@function
XtWindowToWidget:
	jmp *.L_XtWindowToWidget
.L_XtWindowToWidget: .long 0x08656ce0

